---

- name: copy rpm repo to repo list from files
  copy: src=grafana.repo dest=/etc/yum.repos.d/grafana.repo owner=root group=grafana mode=0775
  become: true

- name: install grafana from the repo added
  yum:
   name: grafana
   state: installed
  become: true

- name: install initscripts
  yum: pkg=initscripts state=present
  become: true

- name: install fontconfig
  yum: pkg=fontconfig state=present
  become: true

- name: Create grafana Dashboard directory
  file:
    path: /var/lib/grafana/dashboards
    state: directory
    mode: 0755

- name: Add Dashboard to grafana
  copy:
    src: "{{ item }}"
    dest: /var/lib/grafana/dashboards/
    owner: grafana
    group: grafana
  with_items:
    - mongodb.json
    - mysql.json
    - node-exporter.json
    - prometheus-redis.json
    - tomcat.json

- name: Add Grafana Configuration File
  copy:
    src: grafana.ini
    dest: /etc/grafana/
    owner: grafana
    group: grafana

- name: Adding Conf to enable dashboards
  copy:
    src: all.yml
    dest: /etc/grafana/provisioning/dashboards/
    owner: grafana
    group: grafana

- name: Adding Datasource to Prometheus
  template:
    src: all.yml.j2
    dest: /etc/grafana/provisioning/datasources/all.yml
    owner: grafana
    group: grafana
    
- name: Start Grafana Server
  systemd:
    state: restarted
    daemon_reload: yes
    name: grafana-server
    enabled: yes


