{
 "title": "Tomcat",
 "description": "Tomcat Dashboard (Micrometer.io)",
 "tags": [
  "prometheus",
  "tomcat",
  "micrometer",
  "spring boot"
 ],
 "time": { "from": "now-1h", "to": "now" },
 "refresh": "5s",
 "templating": {
  "list": [
   { "name": "application", "label": "Application", "query": "label_values(application)" },
   {
    "name": "region",
    "label": "Region",
    "query": "label_values(tomcat_threads_config_max{application=\"$application\"}, region)"
   },
   {
    "name": "instance",
    "label": "Instance",
    "query": "label_values(tomcat_threads_config_max{application=\"$application\", region=\"$region\"}, instance)"
   }
  ]
 },
 "panels": [
  { "title": "Threads", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 } },
  {
   "title": "Tomcat Threads",
   "type": "graph",
   "gridPos": { "h": 9, "w": 24, "x": 0, "y": 1 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "tomcat_threads_current{application=\"$application\", region=\"$region\", instance=~\"$instance\"}",
     "legendFormat": "Current threads"
    },
    {
     "expr": "tomcat_threads_busy{application=\"$application\", region=\"$region\", instance=~\"$instance\"}",
     "legendFormat": "Current threads busy"
    }
   ]
  },
  { "title": "Servlets", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 10 } },
  {
   "title": "Total Errors",
   "type": "singlestat",
   "gridPos": { "h": 4, "w": 5, "x": 0, "y": 11 },
   "format": "none",
   "valueName": "avg",
   "targets": [
    {
     "expr": "tomcat_servlet_error_total{application=\"$application\", region=\"$region\", instance=~\"$instance\"}"
    }
   ]
  },
  {
   "title": "Average Processing Time",
   "type": "graph",
   "gridPos": { "h": 8, "w": 19, "x": 5, "y": 11 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "rate(tomcat_servlet_request_seconds_sum{application=\"$application\", region=\"$region\", instance=~\"$instance\"}[5m]) / rate(tomcat_servlet_request_seconds_count{application=\"$application\", region=\"$region\", instance=~\"$instance\"}[5m])",
     "legendFormat": "Response time"
    }
   ]
  },
  {
   "title": "Max time",
   "type": "singlestat",
   "gridPos": { "h": 4, "w": 5, "x": 0, "y": 15 },
   "format": "dtdurations",
   "valueName": "avg",
   "targets": [
    {
     "expr": "tomcat_servlet_request_max_seconds{application=\"$application\", region=\"$region\", instance=~\"$instance\"}"
    }
   ]
  },
  { "title": "Cache", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 19 } },
  {
   "title": "Cache Hit / Total",
   "type": "graph",
   "gridPos": { "h": 6, "w": 24, "x": 0, "y": 20 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "tomcat_cache_access_total{application=\"$application\", region=\"$region\", instance=~\"$instance\"}",
     "legendFormat": "Cache total"
    },
    {
     "expr": "tomcat_cache_hit_total{application=\"$application\", region=\"$region\", instance=~\"$instance\"}",
     "legendFormat": "Cache hits"
    }
   ]
  },
  { "title": "Sessions", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 26 } },
  {
   "title": "Total Created",
   "type": "singlestat",
   "gridPos": { "h": 3, "w": 6, "x": 0, "y": 27 },
   "format": "none",
   "valueName": "avg",
   "targets": [
    {
     "expr": "tomcat_sessions_created_total{application=\"$application\", region=\"$region\", instance=~\"$instance\"}"
    }
   ]
  },
  {
   "title": "Total Rejected",
   "type": "singlestat",
   "gridPos": { "h": 3, "w": 6, "x": 6, "y": 27 },
   "format": "none",
   "valueName": "avg",
   "targets": [
    {
     "expr": "tomcat_sessions_rejected_total{application=\"$application\", region=\"$region\", instance=~\"$instance\"}"
    }
   ]
  },
  {
   "title": "Total Expired",
   "type": "singlestat",
   "gridPos": { "h": 3, "w": 6, "x": 12, "y": 27 },
   "format": "none",
   "valueName": "avg",
   "targets": [
    {
     "expr": "tomcat_sessions_expired_total{application=\"$application\", region=\"$region\", instance=~\"$instance\"}"
    }
   ]
  },
  {
   "title": "Max Alive",
   "type": "singlestat",
   "gridPos": { "h": 3, "w": 6, "x": 18, "y": 27 },
   "format": "dtdurations",
   "valueName": "avg",
   "targets": [
    {
     "expr": "tomcat_sessions_alive_max_seconds{application=\"$application\", region=\"$region\", instance=~\"$instance\"}"
    }
   ]
  },
  {
   "title": "Sessions",
   "type": "graph",
   "gridPos": { "h": 8, "w": 24, "x": 0, "y": 30 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "tomcat_sessions_active_max{application=\"$application\", region=\"$region\", instance=~\"$instance\"}",
     "legendFormat": "Max"
    },
    {
     "expr": "tomcat_sessions_active_current{application=\"$application\", region=\"$region\", instance=~\"$instance\"}",
     "legendFormat": "Current"
    }
   ]
  },
  { "title": "Misc.", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 38 } },
  {
   "title": "Bytes Sent & Received/sec",
   "type": "graph",
   "gridPos": { "h": 9, "w": 24, "x": 0, "y": 39 },
   "yaxes": [
    { "format": "decbytes" }
   ],
   "targets": [
    {
     "expr": "rate(tomcat_global_sent_bytes_total{application=\"$application\", region=\"$region\", instance=~\"$instance\"}[5m])",
     "legendFormat": "Bytes sent"
    },
    {
     "expr": "rate(tomcat_global_received_bytes_total{application=\"$application\", region=\"$region\", instance=~\"$instance\"}[5m])",
     "legendFormat": "Bytes received"
    }
   ]
  }
 ]
}